version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "malik672"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      alloy:
        patterns:
          - "alloy*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      security-updates:
        dependency-type: "security"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"