# cargo-deny configuration for supply chain security

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", 
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "OpenSSL",
    "Zlib",
]
exceptions = [
    { allow = ["OpenSSL"], name = "ring" },
]

[bans]
multiple-versions = "warn"

[advisories]
ignore = [
    # Allow unmaintained dependencies that are part of alloy ecosystem
    # These are stable and widely used despite maintenance status
    "RUSTSEC-2024-0436",  # paste - used by alloy-sol-types, stable proc macro
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]