[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
mordor = { path = "../mordor" }
alloy.workspace = true
alloy-primitives.workspace = true
serde.workspace = true
memchr.workspace = true
tree_hash_derive.workspace = true
tree_hash.workspace = true